config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations", sessions: "sessions" }
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      post :ask_for_code, to: "users#ask_for_code"
      post :accept_request, to: "users#accept_request"
      post :decline_request, to: "users#decline_request"
    end
  end
  get '/api', to: "users#api"
  authenticated :user do
    root to: "users#index", as: :authenticated_root
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  after_create :send_friend_request_email

  validates_presence_of :sender, :receiver
  validate :no_reciprocity

  def no_reciprocity
    if Friendship.where(receiver: sender, sender: receiver).any?
      errors.add :sender, "Friendship already exists"
    end
  end

  private

  def send_friend_request_email
    FriendMailer.friend_request(self).deliver unless receiver.email.nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  devise :omniauthable, :omniauth_providers => [ :facebook ]

  include AlgoliaSearch

  algoliasearch index_name: "#{self}#{ENV['ALGOLIA_SUFFIX']}" do
    attribute :name, :picture, :digicode
    attributesToIndex ['name']
  end

  def friends
    output = []
    friendships.each { |friendship| friendship.sender == self ? (output << friendship.receiver) : (output << friendship.sender) }
    output
  end

  def users_who_asked_me
    output = []
    pending_friendships.each { |friendship| output << friendship.sender if friendship.receiver == self }
    output
  end

  def users_i_asked
    output = []
    pending_friendships.each { |friendship| output << friendship.receiver if friendship.sender == self }
    output
  end

  def pending_friends
    output = []
    pending_friendships.each { |friendship| friendship.sender == self ? (output << friendship.receiver) : (output << friendship.sender) }
    output
  end

  def friendships
    Friendship.where("(sender_id = :id OR receiver_id = :id) AND accepted = true", id: id)
  end

  def declined_friendships
    Friendship.where("(sender_id = :id OR receiver_id = :id) AND accepted = false", id: id)
  end

  def pending_friendships
    Friendship.where("(sender_id = :id OR receiver_id = :id)", id: id) - friendships - declined_friendships
  end

  def friends_with?(user)
    (friends.include? user) ? true : false
  end

  def pending_friends_with?(user)
    (pending_friends.include? user) ? true : false
  end

  def has_asked_friendship_to?(user)
    Friendship.find_by(sender_id: id, receiver_id: user.id) ? true : false
  end

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.name = auth.info.name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  before_action :authenticate_user!, unless: :pages_controller?

  after_action :verify_authorized, except:  :index, unless: :devise_or_pages_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_or_pages_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def devise_or_pages_controller?
    devise_controller? || pages_controller?
  end

  def after_sign_up_path_for(resource)
    edit_user_path(resource) if request.env['omniauth.origin']
  end

  def after_sign_in_path_for(resource)
    if (request.env['omniauth.origin'] && resource.digicode.nil?)
      edit_user_path(resource)
    else
      users_path
    end
  end

  def pages_controller?
    controller_name == "pages"  # Brought by the `high_voltage` gem
  end

  def user_not_authorized
    flash[:error] = I18n.t('controllers.application.user_not_authorized', default: "You can't access this page.")
    redirect_to(root_path)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    edit_user_path(resource) if request.env['omniauth.origin']
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    params[:user].merge!(remember_me: 1)
    super
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Devise::Controllers::Rememberable
  def facebook
    user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      remember_me(user)
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :api]
  after_action :verify_authorized, except: :index, unless: :devise_controller?

  def index
    @users = policy_scope(User)
  end

  def show
    authorize @user
  end

  def edit
    authorize @user
    flash.now["notice"] = "Your code will only be shared to users you accepted / asked as friends"
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to users_path
      flash.now["notice"] = "Your code has been saved"
    else
      render :edit
    end
  end

  def ask_for_code
    if Friendship.find_by(sender: current_user, receiver: @user)
      @friendship = Friendship.find_by(sender: current_user, receiver: @user)
      @friendship.accepted = nil
    elsif Friendship.find_by(sender: @user, receiver: current_user)
      @friendship = Friendship.find_by(sender: @user, receiver: current_user)
      @friendship.accepted = nil
    else
      @friendship = Friendship.new(sender: current_user, receiver: @user)
    end
    if @friendship.save
      respond_to do |format|
        format.html { redirect_to users_path }
        format.js
      end
    else
      redirect_to :back
    end
    authorize @user
  end

  def accept_request
    @friendship = Friendship.find_by(sender: @user, receiver: current_user)
    @friendship.accepted = true
    if @friendship.save
      respond_to do |format|
        format.html { redirect_to users_path }
        format.js
      end
    else
      redirect_to :back
    end
    authorize @user
  end

  def decline_request
    @friendship = Friendship.find_by(sender: @user, receiver: current_user)
    @friendship.accepted = false
    if @friendship.save
      respond_to do |format|
        format.html { redirect_to users_path }
        format.js
      end
    else
      redirect_to :back
    end
    authorize @user
  end

  def api
    @users = User.all.reject { |u| u == current_user }.sort_by(&:name)
    @user = current_user
    authorize @user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:digicode)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <meta name="description" content="<%= yield(:description) %>">

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <!-- FACEBOOK -->
  <meta property="og:title" content="Digicode">
  <meta property="og:image" content="http://www.pix-host.com/allimages/80495005.png">
  <meta property="og:description" content="The only place to store your friends' digicodes">
  <meta property="og:site_name" content="Digicode"/>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

  <%= yield %>

  <%= javascript_include_tag :application %>
  <%= yield(:after_js) %>

</body>
</html>

app/views/pages/home.html.erb
<%= content_for(:title) do %>
  Digicode
<% end %>

<%= content_for(:description) do %>
  The one and only web app to store your friends' digicodes !
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 padding-sides-15 text-center">
      <div class="panel panel-default max-width-328 margin-15-auto">
        <div class="panel-body">
          <div class="row margin-top-15">
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">1</a>
            </div>
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">2</a>
            </div>
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">3</a>
            </div>
          </div>
          <div class="row margin-top-15">
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">4</a>
            </div>
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">5</a>
            </div>
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">6</a>
            </div>
          </div>
          <div class="row margin-top-15">
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">7</a>
            </div>
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">8</a>
            </div>
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">9</a>
            </div>
          </div>
          <div class="row margin-top-15">
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">A</a>
            </div>
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">0</a>
            </div>
            <div class="col-xs-4 text-center">
              <a href="#" class="btn btn-figure">B</a>
            </div>
          </div>
          <div class="row margin-top-15 text-center">
            <%= link_to user_omniauth_authorize_path(:facebook), class: "btn btn-facebook" do %>
              Connect with <i class="fa fa-facebook-square"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 padding-sides-15">
      <% if notice %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navigation-bar">
  <div class="container padding-sides-15">
    <div class="brand">
      <%= link_to users_path, class: "logo" do %>
        Digi<b>code</b>
      <% end %>
      <div class='slogan'>
        The only place to find your friends' digicodes
      </div>
    </div>
    <div class="bar-right pull-right">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <div class="img-avatar">
                <%= image_tag current_user.picture, { class: "img total-width border-radius-2" } %>
              </div>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Browse users', users_path %></li>
              <li><%= link_to 'Update my digicode', edit_user_path(current_user) %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <div class="button margin-right-0 slide-down">
          <%= link_to user_omniauth_authorize_path(:facebook), class: "btn btn-facebook" do %>
            Connect with <i class="fa fa-facebook-square"></i>
          <% end %>
        </div>
      <% end %>
      <div class="nav-link">
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="row" id="<%= "user_#{user.id}" %>">
  <div class="col-xs-12 margin-top-15">
    <%= link_to "", user_path(user), class: 'link-user' if current_user.friends_with?(user) %>
    <div class="col-xs-9">
      <ul class="list-unstyled list-inline">
        <li>
          <%= image_tag user.picture, class: "img width-40 border-radius-2" %>
        </li>
        <li class="name">
          <%= user.name %>
        </li>
      </ul>
    </div>
    <div class="col-xs-3">
      <ul class="list-unstyled list-inline height-40">
        <% if current_user.friends_with?(user) %>
          <li class="pull-right padding-right-none sent">
            <%= user.digicode %>
          </li>
        <% elsif current_user.has_asked_friendship_to?(user) %>
          <li class="pull-right padding-right-none sent">
            Sent
          </li>
        <% elsif current_user.pending_friends_with?(user) %>
          <li class="pull-right padding-right-none" id="<%= "no_#{user.id}" %>">
            <%= link_to decline_request_user_path(user), method: :post, remote: true, class: "btn btn-no" do %>
              <i class="fa fa-close"></i>
            <% end %>
          </li>
          <li class="pull-right" id="<%= "yes_#{user.id}" %>">
            <%= link_to accept_request_user_path(user), method: :post, remote: true, class: "btn btn-yes" do %>
              <i class="fa fa-check"></i>
            <% end %>
          </li>
        <% else %>
          <li class="pull-right padding-right-none" id="<%= "ask_#{user.id}" %>">
            <%= link_to ask_for_code_user_path(user), method: :post, remote: true, class: "btn btn-ask" do %>
              Add<span class="hidden-xs"> as friend</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/accept_request.js.erb
<% if @friendship.errors.any? %>

<% else %>
  $("<%= "#yes_#{@friendship.sender.id}" %>").addClass('padding-right-none').addClass('sent').html('<%= @friendship.sender.digicode %>');
  $("<%= "#no_#{@friendship.sender.id}" %>").remove();
<% end %>

app/views/users/ask_for_code.js.erb
<% if @friendship.errors.any? %>

<% else %>
  $("<%= "#ask_#{@friendship.receiver.id}" %>").html('Sent');
<% end %>

app/views/users/decline_request.js.erb
<% if @friendship.errors.any? %>

<% else %>
  $("<%= "#no_#{@friendship.sender.id}" %>").html('<%= link_to ask_for_code_user_path(@friendship.sender), method: :post, remote: true, class: "btn btn-ask" do %>Add<span class="hidden-xs"> as friend</span><% end %>');
  $("<%= "#yes_#{@friendship.sender.id}" %>").remove();
<% end %>

app/views/users/edit.html.erb
<%= content_for(:title) do %>
  Digicode
<% end %>

<%= content_for(:description) do %>
  Update your digicode in order to be
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 padding-sides-15">
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :digicode, "Digicode" %>
          <%= f.text_field :digicode, class: "form-control" %>
        </div>
        <%= f.submit "Enregistrer", class: "btn btn-submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= content_for(:title) do %>
  Digicode
<% end %>

<%= content_for(:description) do %>
  Browse users and add people as friends to share your digicodes
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 padding-sides-15">
      <div class="search-bar">
        <div class="input-group input-group m-t">
          <input type="text" name="q" id="q" autocomplete="off" spellcheck="false" autocorrect="false" class="form-control string" placeholder="Type someone's name..." />
          <span class="input-group-addon"><i class="fa fa-search"></i></span>
        </div>
      </div>
    </div>
    <div class="col-xs-12 padding-sides-15">
      <div id="hits">
      </div>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  </script>
  <!-- Hogan -->
  <script src="//cdn.jsdelivr.net/hogan.js/3.0.0/hogan.common.js"></script>
  <!-- Algolia -->
  <script src="//cdn.jsdelivr.net/algoliasearch/latest/algoliasearch.js"></script>
  <script type="text/template" id="hit-template">
    <div class="row" id="user_{{ objectID }}">
      <div class="col-xs-12 margin-top-15">
        {{#friends}}
          <a class="link-user" href="{{ user_url }}"></a>
        {{/friends}}
        <div class="col-xs-9">
          <ul class="list-unstyled list-inline">
            <li>
              <img class="img width-40 border-radius-2" src="{{ picture }}" alt="{{ name }}" >
            </li>
            <li class="name">
               {{{ _highlightResult.name.value }}}
            </li>
          </ul>
        </div>
        <div class="col-xs-3">
          <ul class="list-unstyled list-inline height-40">
            {{#friends}}
              <li class="pull-right padding-right-none sent">
                {{ digicode }}
              </li>
            {{/friends}}
            {{^friends}}
              {{#hasAsked}}
                <li class="pull-right padding-right-none sent">
                  Sent
                </li>
              {{/hasAsked}}
              {{^hasAsked}}
                {{#wasAsked}}
                  <li class="pull-right padding-right-none" id="no_{{ objectID }}">
                    <a href="{{ decline_url }}", data-method="post"data-remote=true class="btn btn-no">
                      <i class="fa fa-close"></i>
                    </a>
                  </li>
                  <li class="pull-right" id="yes_{{ objectID }}">
                    <a href="{{ accept_url }}" data-method="post" data-remote=true class="btn btn-yes">
                      <i class="fa fa-check"></i>
                    </a>
                  </li>
                {{/wasAsked}}
                {{^wasAsked}}
                  <li class="pull-right padding-right-none" id="ask_{{ objectID }}">
                    <a href="{{ ask_url }}" data-method="post" data-remote=true class="btn btn-ask">
                      Add<span class="hidden-xs"> as friend</span>
                    </a>
                  </li>
                {{/wasAsked}}
              {{/hasAsked}}
            {{/friends}}
          </ul>
        </div>
      </div>
    </div>
  </script>
  <%= javascript_tag do %>
    $(document).ready(function() {
      initAlgolia(
        '<%= ENV['ALGOLIA_APPLICATION_ID'] %>',
        '<%= ENV['ALGOLIA_SEARCH_ONLY_API_KEY'] %>',
        'User<%= ENV['ALGOLIA_SUFFIX']%>',
        '<%= current_user.id %>',
        "<%= user_path(id: ":id") %>",
        "<%= ask_for_code_user_path(id: ":id") %>",
        "<%= accept_request_user_path(id: ":id") %>",
        "<%= decline_request_user_path(id: ":id") %>",
        '<%= current_user.friends.map { |f| f.id } %>',
        '<%= current_user.users_i_asked.map { |f| f.id } %>',
        '<%= current_user.users_who_asked_me.map { |f| f.id } %>'
      );
    })
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 padding-sides-15 text-center">
      <div class="digicode">
        <%= @user.digicode %>
      </div>
    </div>
  </div>
</div>